### ISSUE TITLE
Redirect handling

### ISSUE THREAD

**Issue by toabi** [minio/minio-go#1465]
I have a weird issue I noticed when trying out [terraform-provider-minio](https://github.com/aminueza/terraform-provider-minio) which uses this library.

I deployed minio with the [minio operator](https://github.com/minio/operator) and created an ingress for it. Inside the cluster in runs on cert-manager provided TLS certificates.

```
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    name: cdn
    namespace: minio
  spec:
    rules:
    - host: minio.stage.my.domain
       http:
         paths:
         - backend:
             service:
               name: minio
               port:
                 number: 9000
    tls:
    - hosts:
      - minio.stage.my.domain
      secretName: cdn-ingress
```

The weird thing is: If I use the terraform module, it can create buckets and files without problems. But as soon as I want to create users and policies I get a JSON parse error.

I dug a bit deeper and the reason is that the nginx ingress returns a "HTTP 308" with the following headers:

    Connection:[keep-alive]
    Content-Length:[164]
    Content-Type:[text/html]
    Date:[Thu, 18 Mar 2021 07:11:26 GMT]
    Location:[https://minio.stage.mecodia.cloud/minio/admin/v3/add-user?accessKey=minio_user2]

The page also contains the default nginx redirect html page so parsing that JSON fails and raises an error which bubbles up to the provider.

If I do a port-forward to localhost and run the provider against localhost instead of the public domain, it can also create users/policies.

I'm now not 100% sure were to file this. It *can* create buckets/files so I wonder if somewhere it follows redirects and somewhere not?
