### ISSUE TITLE
AWS Region Issues

### ISSUE THREAD

**Issue by valentinedwv** [minio/minio-go#1842]
github.com/minio/minio-go/v7 v7.0.52
github.com/aws/aws-sdk-go v1.44.286

Having issues with aws regions.

The auth is in one zone, and the bucket is in another.

```
minioClient, err = minio.New(endpoint,
			&minio.Options{Creds: credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
				Secure: useSSL,
				Region: region,
			})
buckets, err := mc.ListBuckets(context.Background())
```

Call to list buckets fails with an auth error.

 
```
minio:
    address: s3.amazonaws.com
    port: 443
    ssl: true
    accesskey:
    secretkey:
    bucket: ec-geocodes
    region: us-west-2
```

.The authorization header is malformed; the region 'us-west-2' is wrong; expecting 'us-east-1'"

```
minio:
    address: s3.us-west-2.amazonaws.com
    port: 443
    ssl: true
    accesskey:
    secretkey: 
    bucket: ec-geocodes
    region: us-east-1
```
The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'

```
minio:
    address: s3.us-west-2.amazonaws.com
    port: 443
    ssl: true
    accesskey:
    secretkey: 
    bucket: ec-geocodes
    region: us-west-2
```
This does work
