### ISSUE TITLE
Credential is mal-formed error while running in Docker Compose 

### ISSUE THREAD

**Issue by Southclaws** [minio/minio-go#984]
Hi, I'm in the midst of moving some of my side projects from regular `docker run` scripts to Docker Compose. I've gotten stuck while moving one app that uses Minio, it encounters this error on launch:

```
Error parsing the X-Amz-Credential parameter; the Credential is mal-formed; expecting \"<YOUR-AKID>/YYYYMMDD/REGION/SERVICE/aws4_request\".
```

My old, fairly simple deployment method was simple a run command:

```
docker run \
	--name minio \
	--detach \
	--publish 9001:9000 \
	--volume /data/minio:/data \
	minio/minio \
	server /data
docker network connect minio minio
```

There's a network named `minio` which both the Minio and my app container are connected to, the app simply connects to `http://minio:9000` and everything works fine.

In compose however, this isn't working as expect and I'm not sure why. I'm fairly certain everything is set up the same, there's a minio network:

```yml
networks:
    minio:
        driver: bridge
        internal: true
```

And the minio service:

```yml
    minio:
        image: minio/minio
        command: server /data
        volumes:
            - '/data/minio:/data'
        networks:
            - minio
```

Could this be related to the fact that I'm using a domain name to access the container and minio isn't aware of that or something?
